//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonJuan_Inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASISTENCIA
    {
        public int ASISTENCIA_ID { get; set; }
        public int EMPLEADO_ID { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<System.DateTime> HORA_ENTRADA { get; set; }
        public Nullable<System.DateTime> HORA_SALIDA { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
    }
}
