//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonJuan_Inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public string NOMBRE { get; set; }
        public byte[] TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> ESTILISTA { get; set; }
        public string RFC { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<int> CODIGO_POSTAL { get; set; }
        public string CIUDAD { get; set; }
        public string ESTADO { get; set; }
        public int CLIENTE_ID { get; set; }
    }
}
