//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonJuan_Inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public int CLIENTE_ID { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> ESTILISTA { get; set; }
        public string RFC { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<int> CODIGO_POSTAL { get; set; }
        public string CIUDAD { get; set; }
        public string ESTADO { get; set; }
    }
}
