//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonJuan_Inventario
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_DONJUANEntities : DbContext
    {
        public BD_DONJUANEntities()
            : base("name=BD_DONJUANEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ASISTENCIA> ASISTENCIAs { get; set; }
        public virtual DbSet<COMPRA> COMPRAs { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADOes { get; set; }
        public virtual DbSet<FACTURACION> FACTURACIONs { get; set; }
        public virtual DbSet<INVENTARIO> INVENTARIOs { get; set; }
        public virtual DbSet<NOMINA> NOMINAs { get; set; }
        public virtual DbSet<PEDIDO> PEDIDOes { get; set; }
        public virtual DbSet<PEDIDO_RECIBIDO> PEDIDO_RECIBIDO { get; set; }
        public virtual DbSet<PEDIDO_RECIBIDO_PRODUCTO> PEDIDO_RECIBIDO_PRODUCTO { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTOes { get; set; }
        public virtual DbSet<PRODUCTO_MOVIMIENTO> PRODUCTO_MOVIMIENTO { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDORs { get; set; }
        public virtual DbSet<PUESTO> PUESTOes { get; set; }
        public virtual DbSet<STOCK> STOCKs { get; set; }
        public virtual DbSet<VENTA> VENTAs { get; set; }
        public virtual DbSet<VENTA_PRODUCTO> VENTA_PRODUCTO { get; set; }
        public virtual DbSet<CATEGORIA> CATEGORIAs { get; set; }
        public virtual DbSet<CLIENTE> CLIENTEs { get; set; }
    }
}
