//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonJuan_Inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURACION
    {
        public int FACTURACION_ID { get; set; }
        public int VENTA_ID { get; set; }
        public int CLIENTE_ID { get; set; }
    
        public virtual VENTA VENTA { get; set; }
    }
}
