//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonJuan_Inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO
    {
        public int INVENTARIO_ID { get; set; }
        public int PRODUCTO_ID { get; set; }
        public int CANTIDAD { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
