//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonJuan_Inventario
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class INVENTARIO
    {
        [DisplayName("ID Inventario")]
        public int INVENTARIO_ID { get; set; }
        [DisplayName("ID Producto")]
        public int PRODUCTO_ID { get; set; }
        [DisplayName("Cantidad")]
        public int CANTIDAD { get; set; }
        [System.ComponentModel.Browsable(false)]
        public virtual PRODUCTO PRODUCTO { get; set; }

        [DisplayName("Producto")]
        public string ProductName
        {
            get { return PRODUCTO.NOMBRE; }
        }
    }
}
