//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonJuan_Inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOMINA
    {
        public int NOMINA_ID { get; set; }
        public int EMPLEADO_ID { get; set; }
        public Nullable<decimal> SUELDO_TOTAL { get; set; }
        public Nullable<decimal> BONO { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
    }
}
