//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonJuan_Inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO_RECIBIDO_PRODCUTO
    {
        public int PEDIDO_REC_PRODCUTO_ID { get; set; }
        public int PEDIDO_REC_ID { get; set; }
        public int PRODUCTO_ID { get; set; }
        public int CANTIDAD { get; set; }
    
        public virtual PEDIDO_RECIBIDO PEDIDO_RECIBIDO { get; set; }
    }
}
