//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonJuan_Inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO_RECIBIDO_PRODUCTO
    {
        public int PEDIDO_REC_PRODUCTO_ID { get; set; }
        public int PEDIDO_REC_ID { get; set; }
        public int PRODUCTO_ID { get; set; }
        public int CANTIDAD { get; set; }
    
        public virtual PEDIDO_RECIBIDO PEDIDO_RECIBIDO { get; set; }
    }
}
