//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonJuan_Inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO_MOVIMIENTO
    {
        public int PRODUCTO_MOVIMIENTO_ID { get; set; }
        public int PRODUCTO_ID { get; set; }
        public int PROVEEDOR_ID { get; set; }
        public int COMPRA_ID { get; set; }
        public int PEDIDO_ID { get; set; }
        public int CANTIDAD { get; set; }
        public string TIPO { get; set; }
    
        public virtual COMPRA COMPRA { get; set; }
        public virtual PEDIDO PEDIDO { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
