//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonJuan_Inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO_MOVIMIENTO
    {
        public int PRODUCTO_MOVIMIENTO_ID { get; set; }
        public Nullable<int> PRODUCTO_ID { get; set; }
        public Nullable<int> PROVEEDOR_ID { get; set; }
        public Nullable<int> COMPRA_ID { get; set; }
        public Nullable<int> PEDIDO_ID { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public string TIPO { get; set; }
    
        public virtual COMPRA COMPRA { get; set; }
        public virtual PEDIDO PEDIDO { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
