--
-- Script was generated by Devart dbForge Studio for SQL Server, Version 5.4.275.0
-- Product home page: http://devart.com/dbforge/sql/studio
-- Script date 05/26/2017 12:09:20 PM
-- Server version: 12.00.0304
-- Client version: 
-- Please backup your database before running this script
--

--
-- Start Transaction
--
BEGIN TRANSACTION
GO

--
-- Create column [CODIGO] on table [dbo].[PRODUCTO]
--
ALTER TABLE dbo.PRODUCTO
  ADD CODIGO varchar(500) NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Commit Transaction
--
IF @@TRANCOUNT>0 COMMIT TRANSACTION
GO

--
-- Set NOEXEC to off
--
SET NOEXEC OFF
GO