CREATE DATABASE BD_DONJUAN;

USE BD_DONJUAN;


CREATE TABLE PUESTO(
PUESTO_ID INT NOT NULL,
TIPO_PUESTO VARCHAR(30),
SUELDO_BASE MONEY,
PRIMARY KEY(PUESTO_ID));


CREATE TABLE EMPLEADO(
EMPLEADO_ID INT NOT NULL,
PUESTO_ID INT NOT NULL,
NOMBRE VARCHAR(30),
RFC VARCHAR(12),
DIRECCION VARCHAR(50),
TELEFONO VARCHAR(30),
FOREIGN KEY (PUESTO_ID) REFERENCES PUESTO(PUESTO_ID) ON DELETE CASCADE,
PRIMARY KEY(EMPLEADO_ID));


CREATE TABLE ASISTENCIA(
ASISTENCIA_ID INT NOT NULL,
EMPLEADO_ID INT NOT NULL,
FECHA DATE,
HORA_ENTRADA DATE,
HORA_SALIDA DATE,
FOREIGN KEY (EMPLEADO_ID) REFERENCES EMPLEADO(EMPLEADO_ID) ON DELETE CASCADE,
PRIMARY KEY(ASISTENCIA_ID));


CREATE TABLE NOMINA(
NOMINA_ID INT NOT NULL,
EMPLEADO_ID INT NOT NULL,
SUELDO_TOTAL MONEY,
BONO MONEY,
FOREIGN KEY (EMPLEADO_ID) REFERENCES EMPLEADO(EMPLEADO_ID) ON DELETE CASCADE,
PRIMARY KEY(NOMINA_ID));


CREATE TABLE CLIENTE(
CLIENTE_ID INT NOT NULL,
NOMBRE VARCHAR(30),
TELEFONO VARCHAR(30),
EMAIL VARCHAR(50),
ESTILISTA BIT,
RFC VARCHAR(12),
DIRECCION VARCHAR(50),
CODIGO_POSTAL INT,
CIUDAD VARCHAR(30),
ESTADO VARCHAR(30),
PRIMARY KEY(CLIENTE_ID));


CREATE TABLE VENTA(
VENTA_ID INT NOT NULL,
EMPLEADO_ID INT NOT NULL,
TOTAL MONEY,
FECHA DATE,
DESCUENTO BIT,
FOREIGN KEY (EMPLEADO_ID) REFERENCES EMPLEADO(EMPLEADO_ID) ON DELETE CASCADE,
PRIMARY KEY (VENTA_ID));


CREATE TABLE FACTURACION(
FACTURACION_ID INT NOT NULL,
VENTA_ID INT NOT NULL,
FOREIGN KEY (VENTA_ID) REFERENCES VENTA(VENTA_ID) ON DELETE CASCADE,
PRIMARY KEY (FACTURACION_ID));


CREATE TABLE CATEGORIA(
CATEGORIA_ID INT NOT NULL,
NOMBRE VARCHAR(50),
PRIMARY KEY(CATEGORIA_ID));


CREATE TABLE PROVEEDOR(
PROVEEDOR_ID INT NOT NULL,
NOMBRE VARCHAR(30),
DIRECCION VARCHAR(50),
TELEFONO VARCHAR(30),
RFC VARCHAR(12),
EMAIL VARCHAR(50),
PRIMARY KEY(PROVEEDOR_ID));


CREATE TABLE PRODUCTO(
PRODUCTO_ID INT NOT NULL,
CATEGORIA_ID INT NOT NULL,
PROVEEDOR_ID INT NOT NULL,
NOMBRE VARCHAR(30),
PRECIO MONEY,
COSTO MONEY,
UNIDAD VARCHAR(30),
MARCA VARCHAR(30),
FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA(CATEGORIA_ID) ON DELETE CASCADE,
FOREIGN KEY (PROVEEDOR_ID) REFERENCES PROVEEDOR(PROVEEDOR_ID) ON DELETE CASCADE,
PRIMARY KEY (PRODUCTO_ID));


CREATE TABLE STOCK(
STOCK_ID INT NOT NULL,
PRODUCTO_ID INT NOT NULL,
CANTIDAD INT NOT NULL,
FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTO(PRODUCTO_ID) ON DELETE CASCADE,
PRIMARY KEY (STOCK_ID));


CREATE TABLE VENTA_PRODUCTO(
VENTA_PRODUCTO_ID INT NOT NULL,
VENTA_ID INT NOT NULL,
PRODUCTO_ID INT NOT NULL,
PRECIO_ACTUAL MONEY,
FOREIGN KEY (VENTA_ID) REFERENCES VENTA(VENTA_ID) ON DELETE CASCADE,
FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTO(PRODUCTO_ID) ON DELETE CASCADE,
PRIMARY KEY (VENTA_PRODUCTO_ID));


CREATE TABLE INVENTARIO(
INVENTARIO_ID INT NOT NULL,
PRODUCTO_ID INT NOT NULL,
CANTIDAD INT NOT NULL,
FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTO(PRODUCTO_ID) ON DELETE CASCADE,
PRIMARY KEY (INVENTARIO_ID));


CREATE TABLE PEDIDO(
PEDIDO_ID INT NOT NULL,
ESTADO VARCHAR(50),
FECHA DATE,
PRIMARY KEY (PEDIDO_ID));


CREATE TABLE PEDIDO_RECIBIDO(
PEDIDO_REC_ID INT NOT NULL,
PEDIDO_ID INT NOT NULL,
FECHA DATE,
FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(PEDIDO_ID) ON DELETE CASCADE,
PRIMARY KEY (PEDIDO_REC_ID));


CREATE TABLE PEDIDO_RECIBIDO_PRODCUTO(
PEDIDO_REC_PRODCUTO_ID INT NOT NULL,
PEDIDO_REC_ID INT NOT NULL,
PRODUCTO_ID INT NOT NULL,
CANTIDAD INT NOT NULL,
FOREIGN KEY (PEDIDO_REC_ID) REFERENCES PEDIDO_RECIBIDO(PEDIDO_REC_ID) ON DELETE CASCADE,
PRIMARY KEY (PEDIDO_REC_PRODCUTO_ID));


CREATE TABLE COMPRA(
COMPRA_ID INT NOT NULL,
PROVEEDOR_ID INT NOT NULL,
SUBTOTAL MONEY,
TOTAL MONEY,
ESTADO VARCHAR(30),
FECHA DATE,
FOREIGN KEY (PROVEEDOR_ID) REFERENCES PROVEEDOR(PROVEEDOR_ID) ON DELETE CASCADE,
PRIMARY KEY (COMPRA_ID));


CREATE TABLE PRODUCTO_MOVIMIENTO(
PRODUCTO_MOVIMIENTO_ID INT NOT NULL,
PRODUCTO_ID INT NOT NULL,
PROVEEDOR_ID INT NOT NULL,
COMPRA_ID INT NOT NULL,
PEDIDO_ID INT NOT NULL,
CANTIDAD INT NOT NULL,
TIPO VARCHAR(30),
FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTO(PRODUCTO_ID),
FOREIGN KEY (PROVEEDOR_ID) REFERENCES PROVEEDOR(PROVEEDOR_ID),
FOREIGN KEY (COMPRA_ID) REFERENCES COMPRA(COMPRA_ID),
FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(PEDIDO_ID),
PRIMARY KEY (PRODUCTO_MOVIMIENTO_ID));


